### ISSUE TITLE
Any plan to publish the code?

### ISSUE THREAD

**Issue by sjg02122** [Syniez/SlaBins#2] opened 2024-04-22 01:58 UTC
Hi, thanks for the great work.
Is there any plan about the code publishing?

**Comment by Syniez** [comment] 2024-04-23 08:18
Thank you for your interest.
Unfortunately, the codes are confidential. However, If you want to reproduce our work, we can give you some hints.
Our core codes are based on the previous bin-based monocular depth estimation framework, [AdaBins](https://github.com/shariqfarooq123/AdaBins), and we add some transformation functions(`Euclidean domain` -> `Slanted Cylinder domain`) using pre-computed fisheye lookup-tabels(LUTs). The LUTs are computed same manner as [OmniDet](https://github.com/valeoai/WoodScape/tree/master/omnidet).

**Comment by sjg02122** [comment] 2024-04-29 02:00
Thank you for your answer.

I can understand the confidentiality of the model part. However, I understand that the part about the database used the public dataset. I would appreciate it if you could partially release the part about the dataset.

**Comment by Syniez** [comment] 2024-05-02 11:03
As written in the paper, because of the lack of the SynWoodScape dataset (partially released), we used the [SynWoodScape](https://arxiv.org/abs/2203.05056) and [KITTI-360](https://github.com/autonomousvision/kitti360Scripts) datasets with our angle augmentation. The augmented datasets will be released on this repository within this month.

Thank you.

**Comment by Hubert3123** [comment] 2024-06-11 06:38
> Thank you.

Hi, thanks for the great work and the contribution. Will the augmented datasets be released soon? Thanks.~

**Comment by Syniez** [comment] 2024-06-12 12:37
> > Thank you.
> 
> Hi, thanks for the great work and the contribution. Will the augmented datasets be released soon? Thanks.~

Nowadays, I try to clean up our pre-processing codes and collect our augmented datasets for release. They will be shared soon on this repository. Sorry for being late.

Thank you.

**Comment by RRRed22** [comment] 2024-08-23 01:14
> > > Thank you.
> > 
> > 
> > Hi, thanks for the great work and the contribution. Will the augmented datasets be released soon? Thanks.~
> 
> Nowadays, I try to clean up our pre-processing codes and collect our augmented datasets for release. They will be shared soon on this repository. Sorry for being late.
> 
> Thank you.

Hi there~ Sorry to bother. Will the augmentation code (or dataset) be released soon? Thank you.

**Comment by Syniez** [comment] 2024-08-29 04:54
Dear all, I am sorry for the late release of the dataset.
I just uploaded the datasets and our angle-augmented datasets are now available at [Download Link](https://drive.google.com/drive/folders/1IGWyjdM0R1-OLOIUEXaJl7Sn8oJoAVG_).

If there is any problem, please report it to me for quick debugging.

Thank you.

**Closed as completed** 2024-12-18 07:32 UTC

**Comment by booker-max** [comment] 2024-12-27 08:55
> Dear all, I am sorry for the late release of the dataset. I just uploaded the datasets and our angle-augmented datasets are now available at [Download Link](https://drive.google.com/drive/folders/1IGWyjdM0R1-OLOIUEXaJl7Sn8oJoAVG_).
> 
> If there is any problem, please report it to me for quick debugging.
> 
> Thank you.

Thank you very much for sharing such detailed and extensive data. I have a few questions:

Depth Folder: In the Depth folder, do the .npy files represent distance data or depth data?

SynWoodScape Image Naming: In the SynWoodScape dataset, what do the suffixes in the image names (e.g., FV, MVL, RV, MVR) stand for? For instance, in the image SynWoodScape/RGB/00000_FV_9.999.png, does the 9.999 indicate the field of view (FOV)?

**Comment by Syniez** [comment] 2024-12-27 09:21
**Depth Folder**: In the depth folder, the ground-truth depth map indicates the euclidean distance from the fisheye camera.

**Image Naming**: [FV, MVL, RV, MVR] stand for the front view, left view, rear view, and right view respectively. Additionally, the last number (_e.g.,_ 9.999) denotes  the slanted angle of the camera viewing direction _w.r.t._ the road ground.

Thank you!

**Comment by booker-max** [comment] 2024-12-30 02:54
> **Depth Folder**: In the depth folder, the ground-truth depth map indicates the euclidean distance from the fisheye camera.
> 
> **Image Naming**: [FV, MVL, RV, MVR] stand for the front view, left view, rear view, and right view respectively. Additionally, the last number (_e.g.,_ 9.999) denotes the slanted angle of the camera viewing direction _w.r.t._ the road ground.
> 
> Thank you!
Thank you!
